name: Flutter-CI

# Este 'workflow' é acionado nas submissões dos código para o repositório. 

on:
  push:
    branches:
    - master
    
jobs:
  build:
    # Este 'job' rodará numa máquina virtual baseada em Ubuntu
    runs-on: ubuntu-latest
    steps:

    # Configuração do ambiente Java a fim de realizar o 'build' para a versão Android do app
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    
    # Baixar as dependências do Flutter
    - run: flutter pub get
    
    # Checagem para qualquer problema de formatação no código
    - run: flutter format --set-exit-if-changed .
    
    # Analisa o código em Dart
    - run: flutter analyze .
